[package]
name = "ecs-disk-manager"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[workspace]
members = [ "prober", "types" ]

[dependencies]
disk-prober = { path = "prober" }
disk-types = { path = "types" }
slotmap = "0.3.0"
secstr = "0.3.2"
