[package]
name = "cryptsetup-sys"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "Apache-2.0/MIT"

[build-dependencies]
bindgen = "0.49.2"
pkg-config = "0.3.14"

