[package]
name = "lvmdbus1"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
dbus = "0.6.4"
serde-xml-rs = "0.3.1"
serde = "1.0.92"
serde_derive = "1.0.92"
err-derive = "0.1.5"
