[package]
name = "cryptsetup"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "Apache-2.0/MIT"

[dependencies]
cryptsetup-sys = { path = "sys" }
libc = "0.2.58"
