[package]
name = "disk-prober"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
blkid = { git = "https://github.com/pop-os/blkid" }
disk-types = { path = "../types" }

[dev-dependencies]
prettytable-rs = "0.8.0"
